[Variables]
; ----------------------------------
; Server 1
; ----------------------------------
Server1=Thor
Hide1=0
YPos1=41
SPos1=55
SettingsHide1=0
SettingsShow1=1

; ----------------------------------
; Server 2
; ----------------------------------
Server2=Urtem
Hide2=0
YPos2=10R
SPos2=24R
SettingsHide2=0
SettingsShow2=1

; ----------------------------------
; Server 3
; ----------------------------------
Server3=Suthran
Hide3=0
YPos3=10R
SPos3=24R
SettingsHide3=0
SettingsShow3=1

; ----------------------------------
; Server 4
; ----------------------------------
Server4=Alquima
Hide4=0
YPos4=10R
SPos4=24R
SettingsHide4=0
SettingsShow4=1

; ----------------------------------
; Server 5
; ----------------------------------
Server5=Barus
Hide5=0
YPos5=10R
SPos5=24R
SettingsHide5=0
SettingsShow5=1
